"use client";

import { ExternalLink, MapPin, Moon, Orbit, X } from "lucide-react";
import { useState } from "react";

type Place = { id: string; planet: "Mars" | "Oy"; name: string; coordinates: string; summary: string; source: string; image: string; credit: string; className: string };
const places: Place[] = [
  { id: "jezero", planet: "Mars", name: "Jezero krateri", coordinates: "18.38° N, 78.20° E", summary: "Qadimda ko‘l bo‘lgan bo‘lishi mumkin bo‘lgan krater; Perseverance uning delta qatlamlarini o‘rganadi.", source: "https://science.nasa.gov/photojournal/jezero-crater/", image: "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia25/pia25350/PIA25350.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1439&w=701", credit: "NASA/JPL-Caltech/ASU", className: "mars-photo" },
  { id: "olympus", planet: "Mars", name: "Olympus Mons", coordinates: "22.95° N, 224.76° E", summary: "Quyosh tizimidagi eng katta vulqon. Qirrasidagi qatlamlar lava, chang yoki kul bo‘lishi mumkinligini ko‘rsatadi.", source: "https://science.nasa.gov/photojournal/collapsing-volcano-edge-of-olympus-mons/", image: "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia12/pia12992/PIA12992.jpg?crop=faces%2Cfocalpoint&fit=clip&h=600&w=800", credit: "NASA/JPL-Caltech/University of Arizona", className: "mars-photo" },
  { id: "tycho", planet: "Oy", name: "Tycho krateri", coordinates: "43° S, 11° W", summary: "Yosh, murakkab zarba krateri. Uning markaziy cho‘qqisi va terrasali devorlari juda aniq ko‘rinadi.", source: "https://science.nasa.gov/image-detail/amf-cc06843a-5b68-4cb4-9119-c62e383b54fa/", image: "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/internal_resources/3375/565706main_wac_tycho_highphase.jpg", credit: "NASA/GSFC/Arizona State University", className: "moon-photo" },
  { id: "tycho-floor", planet: "Oy", name: "Tycho tubi", coordinates: "43° S, 11° W", summary: "LRO suratida krater tubidagi toshlar va zarba erigan jinslari ko‘rinadi; sahna eni taxminan 620 metr.", source: "https://science.nasa.gov/photojournal/the-floor-of-tycho/", image: "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia12/pia12941/PIA12941.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1000&w=1000", credit: "NASA/GSFC/Arizona State University", className: "moon-photo" },
];

export default function PlanetPlaces() {
  const [selected, setSelected] = useState<Place | null>(null);
  return <section className="planet-places" id="sayyoralar"><div className="planet-heading"><div><p className="eyebrow"><span/> Sayyora manzillari</p><h2>Yer analogidan<br/><em>asl manzilga.</em></h2></div><p>Yer hududi nimaga o‘xshashligini bilganingizdan keyin Mars va Oydagi real manzil suratlarini oching.</p></div><div className="planet-grid">{places.map((place) => <button className={`planet-card ${place.className}`} key={place.id} onClick={() => setSelected(place)}><img src={place.image} alt={`${place.name}ning NASA surati`} loading="lazy"/><span className="planet-shade"/><span className="planet-chip">{place.planet === "Mars" ? <Orbit size={14}/> : <Moon size={14}/>} {place.planet}</span><span className="planet-card-copy"><b>{place.name}</b><small><MapPin size={12}/>{place.coordinates}</small></span></button>)}</div>{selected && <div className="photo-backdrop" role="presentation" onMouseDown={() => setSelected(null)}><article className="photo-dialog" role="dialog" aria-modal="true" aria-label={`${selected.name} suratlari`} onMouseDown={(event) => event.stopPropagation()}><button className="close-photo" aria-label="Foto oynasini yopish" onClick={() => setSelected(null)}><X size={19}/></button><img src={selected.image} alt={`${selected.name}ning NASA surati`}/><div><span className="planet-chip">{selected.planet}</span><h3>{selected.name}</h3><p className="planet-coordinates"><MapPin size={14}/>{selected.coordinates}</p><p>{selected.summary}</p><small>Rasm: {selected.credit}</small><a href={selected.source} target="_blank" rel="noreferrer">NASA manbasini ochish <ExternalLink size={14}/></a></div></article></div>}</section>;
}
